Algoritmo "primeiro_algoritmo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : João Abelar Costa
// Descrição   : Modelo de algoritmo
// Autor(a)    : Régis Picáz Tavares
// Data atual  : 11/03/2021
Var
// Seção de Declarações das variáveis 
   nota1: inteiro
   nota2: inteiro
   media: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

     media <-  nota1 /nota2
     escreva ("resultado", media)

Fimalgoritmo